#!/bin/bash
find . -type f -iname "*.gif" | sed 's|.*/\(.*\)\.gif|\1|' | sort -f | uniq | sed '/^\s*$/d' | sed -e 's/^/ /' -e 's/$/\n/'
~                                                                                            
